extension=hookphuzz_opcode_phase9.so
hookphuzz_opcode.target_callbacks=WPCF7_REST_Controller::get_contact_forms
opcache.enable=0
opcache.enable_cli=0
opcache.jit=0
variables_order=GPCS
request_order=GP
