<?php
declare(strict_types=1);

function out(array $value, int $code = 0): never { echo json_encode($value, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES), "\n"; exit($code); }
function fail(string $reason, array $extra = []): never { out(['schema_version'=>1,'status'=>'failed','diagnostic'=>['reason'=>$reason]+$extra], 2); }
function readJson(string $path, string $label): array { if (!is_file($path) || !is_readable($path)) fail("missing_$label", ['path'=>$path]); try { $v=json_decode((string)file_get_contents($path),true,512,JSON_THROW_ON_ERROR); } catch (Throwable $e) { fail("malformed_$label", ['path'=>$path]); } if (!is_array($v)) fail("malformed_$label", ['path'=>$path]); return $v; }
function option(array $argv): array { $r=['artifacts'=>[]]; for($i=1;$i<count($argv);$i++){ $a=$argv[$i]; if(!str_starts_with($a,'--') || !isset($argv[$i+1])) fail('invalid_arguments'); $v=$argv[++$i]; if($a==='--callback-registry')$r['registry']=$v; elseif($a==='--discovery-artifact')$r['artifacts'][]=$v; elseif($a==='--output')$r['output']=$v; elseif($a==='--phuzz-output')$r['phuzz']=$v; elseif($a==='--source-resolution')$r['resolution']=$v; else fail('invalid_arguments',['argument'=>$a]); } return $r; }
function keyPath(array $path): string { return implode('',array_map(static fn($x,$i)=>$i===0?(string)$x:'['.$x.']', $path,array_keys($path))); }
function stableId(string $hook,string $callback,string $type): string { return 'p9-'.substr(hash('sha256',$hook."\0".$callback."\0".$type),0,20); }
function entrypoint(string $hook): ?array { if(str_starts_with($hook,'wp_ajax_nopriv_')) return ['entrypoint_type'=>'wp_ajax_nopriv','action'=>substr($hook,15),'requires_auth'=>false]; if(str_starts_with($hook,'wp_ajax_')) return ['entrypoint_type'=>'wp_ajax','action'=>substr($hook,8),'requires_auth'=>true]; return null; }
function validPath(mixed $path): bool { if(!is_array($path)||$path===[])return false; foreach($path as $part) if(!is_string($part)&&!is_int($part))return false; return true; }
function shadowedByNested(array $parameter,array $all): bool { foreach($all as $other) if($other!==$parameter&&$other['source']===$parameter['source']&&count($other['path'])>count($parameter['path'])&&array_slice($other['path'],0,count($parameter['path']))===$parameter['path']) return true; return false; }

$args=option($argv); if(!isset($args['registry'])||!isset($args['output'])||$args['artifacts']===[]) fail('invalid_arguments');
$registry=readJson($args['registry'],'callback_registry'); if(($registry['schema_version']??null)!==1||!is_array($registry['registrations']??null)) fail('malformed_callback_registry');
$placements=[]; if(isset($args['resolution'])) { $resolution=readJson($args['resolution'],'source_resolution'); if(($resolution['status']??null)!=='validated'||!is_array($resolution['accepted_placements']??null)) fail('malformed_source_resolution'); $placements=array_values(array_intersect(['query','body','cookie'],$resolution['accepted_placements'])); if($placements===[]) fail('unresolved_request_source'); }
$byCallback=[]; $unmatched=[];
foreach($args['artifacts'] as $file){ $artifact=readJson($file,'discovery_artifact'); if(($artifact['schema_version']??null)!==3||!is_array($artifact['callback_summaries']??null)||!is_array($artifact['target_loading']??null)) fail('malformed_discovery_artifact',['path'=>$file]); foreach($artifact['callback_summaries'] as $summary){ if(!is_array($summary)||!is_string($summary['callback']??null)||!is_array($summary['unique_parameters']??null)) continue; foreach($summary['unique_parameters'] as $p){ if(!is_array($p)||!in_array($p['source']??null,['GET','POST','COOKIE','REQUEST'],true)||!validPath($p['path']??null)) continue; $forms=$p['access_forms']??[$p['operation']??'read']; if(!is_array($forms)||$forms===[])$forms=['read']; $k=($summary['callback'])."\0".$p['source']."\0".json_encode($p['path']); $old=$byCallback[$k]??['callback'=>$summary['callback'],'source'=>$p['source'],'path'=>$p['path'],'access_forms'=>[],'observed_count'=>0,'helper_depth'=>0,'key_origin'=>null]; $old['access_forms']=array_values(array_unique(array_merge($old['access_forms'],array_values(array_filter($forms,'is_string'))))); sort($old['access_forms']); $old['observed_count']+=(int)($p['observed_count']??1); $old['helper_depth']=max($old['helper_depth'],(int)($p['helper_depth']??0)); if(isset($p['key_origin'])&&is_array($p['key_origin']))$old['key_origin']=$p['key_origin']; $byCallback[$k]=$old; } }
}
$registered=[]; foreach($registry['registrations'] as $r){ if(is_array($r)&&is_string($r['canonical_callback']??null))$registered[$r['canonical_callback']]=true; }
foreach($byCallback as $p) if(!isset($registered[$p['callback']])) $unmatched[]=['classification'=>'unmatched_callback','canonical_callback'=>$p['callback']];
$configs=[];$diagnostics=[]; foreach($registry['registrations'] as $r){ if(!is_array($r)||!is_string($r['hook_name']??null)||!is_string($r['canonical_callback']??null)) { $diagnostics[]=['classification'=>'malformed_registration']; continue; } $ep=entrypoint($r['hook_name']); if($ep===null){$diagnostics[]=['classification'=>'unsupported_entrypoint','reason'=>'unsupported_entrypoint','hook_name'=>$r['hook_name'],'callback'=>$r['canonical_callback']];continue;} $params=array_values(array_filter($byCallback,static fn($p)=>$p['callback']===$r['canonical_callback'])); $params=array_values(array_filter($params,static fn($p)=>!shadowedByNested($p,$params))); if($params===[]){$diagnostics[]=['classification'=>'unmatched_callback','hook_name'=>$r['hook_name'],'callback'=>$r['canonical_callback']];continue;} usort($params,static fn($a,$b)=>[$a['source'],json_encode($a['path'])]<=>[$b['source'],json_encode($b['path'])]); $id=stableId($r['hook_name'],$r['canonical_callback'],$ep['entrypoint_type']); $request=['method'=>'POST','path'=>'/wp-admin/admin-ajax.php','query'=>[],'body'=>['action'=>$ep['action']],'cookies'=>[]]; $discovered=[]; foreach($params as $i=>$p){$effective=['GET'=>'query','POST'=>'body','COOKIE'=>'cookie'][$p['source']]??null; $status=$p['source']==='REQUEST'?'pending':'generated'; $path=keyPath($p['path']); $marker='PHASE9_'.$id.'_'.$i; if($effective!==null)$request[$effective==='cookie'?'cookies':$effective][$path]=$marker; $discovered[]=['observed_source'=>$p['source'],'effective_source'=>$effective,'path'=>$p['path'],'root_name'=>$p['path'][0],'leaf_name'=>$p['path'][count($p['path'])-1],'access_forms'=>$p['access_forms'],'observed_count'=>$p['observed_count'],'helper_depth'=>$p['helper_depth'],'key_origin'=>$p['key_origin'],'generation_status'=>$status,'marker_id'=>$marker,'resolution_status'=>$p['source']==='REQUEST'?'pending':'validated']; }
    $configs[]=['config_id'=>$id,'hook_name'=>$r['hook_name'],'entrypoint_type'=>$ep['entrypoint_type'],'callback'=>$r['canonical_callback'],'authentication'=>['requires_auth'=>$ep['requires_auth'],'credential'=>'redacted'],'request'=>$request,'fixed_parameters'=>[['source'=>'body','path'=>['action']]],'discovered_parameters'=>$discovered,'provenance'=>['registry_schema_version'=>1,'discovery_artifact_schema_version'=>3]];
}
$variants=[]; foreach($configs as $config){ $requestParams=array_values(array_filter($config['discovered_parameters'],static fn($p)=>$p['observed_source']==='REQUEST')); if($requestParams===[]||$placements===[]){$variants[]=$config;continue;} foreach($placements as $placement){$copy=$config;$copy['config_id'].='-'.$placement;$copy['request_variant']=$placement;foreach($copy['discovered_parameters'] as &$p)if($p['observed_source']==='REQUEST'){$p['effective_source']=$placement;$p['generation_status']='generated_variant';$p['resolution_status']='validated';$target=$placement==='query'?'query':($placement==='body'?'body':'cookies');$copy['request'][$target][keyPath($p['path'])]=$p['marker_id'];}unset($p);$variants[]=$copy;} } $configs=$variants;
usort($configs,static fn($a,$b)=>$a['config_id']<=>$b['config_id']); $doc=['schema_version'=>1,'generated_by'=>'hookphuzz_phase9_config_generator','configs'=>$configs,'diagnostics'=>array_merge($diagnostics,$unmatched)]; $json=json_encode($doc,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES); if($json===false||file_put_contents($args['output'],$json)===false)fail('output_write_failed');
if(isset($args['phuzz'])){ $export=['schema_version'=>1,'generated_by'=>'hookphuzz_phase9_phuzz_export','configs'=>[]]; foreach($configs as $c){$body=[];$query=[];$cookie=[];$fuzz=[]; foreach($c['fixed_parameters'] as $f)$body[]=['name'=>keyPath($f['path']),'value'=>$c['request']['body']['action']]; foreach($c['discovered_parameters'] as $p){if($p['effective_source']===null)continue;$name=keyPath($p['path']);$item=['name'=>$name,'seeds'=>[$p['marker_id']]]; if($p['effective_source']==='query')$query[]=$item; elseif($p['effective_source']==='cookie')$cookie[]=$item; else $body[]=$item; $fuzz[]=$name;} $export['configs'][]=['target'=>'http://wordpress'.$c['request']['path'],'methods'=>['POST'],'query_params'=>['data'=>$query],'body_params'=>['data'=>$body,'fixed'=>['action'],'fuzz'=>$fuzz],'cookie_params'=>['data'=>$cookie],'callback_provenance'=>$c['callback'],'hook_provenance'=>$c['hook_name'],'requires_auth'=>$c['authentication']['requires_auth']]; } file_put_contents($args['phuzz'],json_encode($export,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES)); }
out(['schema_version'=>1,'status'=>'generated','configs'=>count($configs),'diagnostics'=>count($doc['diagnostics'])]);
