<?php
declare(strict_types=1);
function arg(string $name): ?string { global $argv; $i=array_search($name,$argv,true); return $i===false?null:($argv[$i+1]??null); }
function pathName(array $path): string { return implode('',array_map(static fn($v,$i)=>$i===0?(string)$v:'['.$v.']',$path,array_keys($path))); }
function writeAtomically(string $path,array $value): void {$tmp=$path.'.tmp.'.getmypid();file_put_contents($tmp,json_encode($value,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);rename($tmp,$path);}
function hasMarker(mixed $value,string $marker): bool { if(is_string($value))return $value===$marker; if(is_array($value))foreach($value as $v)if(hasMarker($v,$marker))return true; return false; }
function eventMatches(array $artifact,array $parameter,string $callback): bool { foreach($artifact['events']??[] as $event){if(($event['callback_context']['root_callback']??null)!==$callback||($event['source']??null)!==$parameter['observed_source']||($event['path']??null)!==$parameter['path'])continue;if(in_array($event['operation']??'', $parameter['access_forms']??['read'],true))return true;}return false; }
$configs=arg('--configs');$artifactDir=arg('--artifact-dir');$output=arg('--output');$base=arg('--base')??'http://enabled';$jar=arg('--cookie-jar');$runId=arg('--run-id');if(!$configs||!$artifactDir||!$output||!$runId){fwrite(STDERR,"invalid arguments\n");exit(2);}try{$document=json_decode((string)file_get_contents($configs),true,512,JSON_THROW_ON_ERROR);}catch(Throwable){fwrite(STDERR,"malformed configs\n");exit(2);}
$results=[];foreach($document['configs']??[] as $index=>$config){$id=$runId.'-replay-'.$index.'-'.substr(hash('sha256',$config['config_id']),0,12);$request=$config['request'];foreach($config['discovered_parameters'] as $p){if(($p['effective_source']??null)===null)continue;$bucket=$p['effective_source']==='query'?'query':($p['effective_source']==='cookie'?'cookies':'body');$request[$bucket][pathName($p['path'])]=$p['marker_id'];}$url=$base.$request['path'].($request['query']?('?'.http_build_query($request['query'],'','&',PHP_QUERY_RFC3986)):'');$bodyFile=tempnam(sys_get_temp_dir(),'p9body');$cmd=['curl','-sS','--max-time','20','-o',$bodyFile,'-w','%{http_code}','-X',$request['method'],'-H','X-Fuzzer-Covid: '.$id,'-H','X-Phase9-Run-ID: '.$runId];foreach($request['cookies'] as $k=>$v){$cmd[]='-b';$cmd[]=$k.'='.$v;}if($jar&&($config['authentication']['requires_auth']??false)){$cmd[]='-b';$cmd[]=$jar;}foreach($request['body'] as $k=>$v){$cmd[]='--data-urlencode';$cmd[]=$k.'='.$v;}$cmd[]=$url;$status=(int)trim((string)shell_exec(implode(' ',array_map('escapeshellarg',$cmd))));$artifactFile=$artifactDir.'/'.$id.'.json';for($i=0;$i<200&&!is_file($artifactFile);$i++)usleep(100000);$found=is_file($artifactFile);try{$artifact=$found?json_decode((string)file_get_contents($artifactFile),true,512,JSON_THROW_ON_ERROR):[];$response=json_decode((string)file_get_contents($bodyFile),true,512,JSON_THROW_ON_ERROR);}catch(Throwable){$artifact=[];$response=[];}$mismatches=[];$valid=0;foreach($config['discovered_parameters'] as $p){$event=eventMatches($artifact,$p,$config['callback']);$marker=hasMarker($response['data']['phase9Markers']??[],$p['marker_id']);if($event&&$marker)$valid++;else $mismatches[]=['path'=>$p['path'],'expected_placement'=>$p['effective_source']??null,'event'=>$event,'marker_observed'=>$marker];}$reached=(bool)array_filter($artifact['events']??[],static fn($e)=>($e['callback_context']['root_callback']??null)===($config['callback']));$expected=count($config['discovered_parameters']);$semantic=$found&&($artifact['request_id']??null)===$id&&($artifact['run_id']??null)===$runId&&$status===200&&$reached&&$valid===$expected;$results[]=['run_id'=>$runId,'config_id'=>$config['config_id'],'request_id'=>$id,'hook_name'=>$config['hook_name'],'callback'=>$config['callback'],'request_variant'=>$config['request_variant']??null,'http_status'=>$status,'artifact_found'=>$found,'callback_reached'=>$reached,'expected_parameters'=>$expected,'validated_parameters'=>$valid,'semantic_equivalent'=>$semantic,'semantic_pass'=>$semantic,'status'=>$semantic?'validated':'failed','mismatches'=>$mismatches];@unlink($bodyFile);}
$summary=['run_id'=>$runId,'total_configs'=>count($results),'validated'=>count(array_filter($results,static fn($r)=>$r['semantic_pass'])),'failed'=>count(array_filter($results,static fn($r)=>!$r['semantic_pass'])),'all_semantic_pass'=>count($results)>0&&count(array_filter($results,static fn($r)=>!$r['semantic_pass']))===0];writeAtomically($output,['schema_version'=>1,'run_id'=>$runId,'results'=>$results,'summary'=>$summary]);if(!$summary['all_semantic_pass'])exit(1);
