<?php
/** Plugin Name: HookPhuzz Phase 10 CF7 REST Observer */
declare(strict_types=1);
const HP10_ROUTE = '/contact-form-7/v1/contact-forms';
const HP10_CALLBACK = 'WPCF7_REST_Controller::get_contact_forms';
const HP10_CAP = 64;
$hp10_doc = ['schema_version'=>1,'events'=>[],'dropped_event_count'=>0,'callback_reached'=>false,'route_registration'=>null];
$hp10_id = static function (): string { $id=$_SERVER['HTTP_X_FUZZER_COVID'] ?? ''; return is_string($id) && preg_match('/^[A-Za-z0-9][A-Za-z0-9_.-]{0,127}$/',$id) ? $id : ''; };
$hp10_identity = static function ($callback): array { if (is_string($callback)) return ['id'=>$callback,'type'=>'function']; if (is_array($callback) && count($callback)===2 && is_string($callback[1])) { $class=is_object($callback[0])?get_class($callback[0]):(is_string($callback[0])?$callback[0]:'unknown'); return ['id'=>$class.'::'.$callback[1],'type'=>is_object($callback[0])?'object_method':'static_method']; } if ($callback instanceof Closure) { $r=new ReflectionFunction($callback); return ['id'=>'Closure@'.basename((string)$r->getFileName()).':'.$r->getStartLine(),'type'=>'closure']; } return ['id'=>'unsupported','type'=>'unsupported']; };
$hp10_add = static function (array $event) use (&$hp10_doc): void { if (count($hp10_doc['events'])>=HP10_CAP) { $hp10_doc['dropped_event_count']++; return; } $hp10_doc['events'][]=$event; };
$hp10_snapshot = static function () use (&$hp10_doc,$hp10_identity): void { foreach ((rest_get_server()->get_routes()[HP10_ROUTE] ?? []) as $entry) { $callback=$hp10_identity($entry['callback'] ?? null); if ($callback['id']!==HP10_CALLBACK) continue; $permission=$hp10_identity($entry['permission_callback'] ?? null); $methods=$entry['methods'] ?? []; $hp10_doc['route_registration']=['namespace'=>'contact-form-7/v1','route'=>HP10_ROUTE,'methods'=>is_array($methods)?array_keys($methods):(array)$methods,'callback_identity'=>$callback,'permission_callback_identity'=>$permission,'registered_arguments'=>$entry['args'] ?? [],'plugin_attribution'=>'contact-form-7/includes/rest-api.php','registration_observed'=>true]; return; } };
if (function_exists('uopz_set_hook')) uopz_set_hook('register_rest_route', static function ($namespace,$route) use (&$hp10_doc): void { if (trim((string)$namespace,'/')==='contact-form-7/v1' && '/'.trim((string)$route,'/')===HP10_ROUTE) $hp10_doc['register_rest_route_hook_seen']=true; });
add_action('rest_api_init', static function () use ($hp10_snapshot,&$hp10_doc,$hp10_add,$hp10_id): void {
 $hp10_snapshot();
 if (!function_exists('uopz_set_hook') || !class_exists('WP_REST_Request') || !class_exists('WPCF7_REST_Controller')) return;
 uopz_set_hook('WPCF7_REST_Controller','get_contact_forms',static function () use (&$hp10_doc,$hp10_id): void { $id=$hp10_id(); if ($id==='') return; $hp10_doc['callback_reached']=true; $hp10_doc['callback']=['request_id'=>$id,'callback_id'=>HP10_CALLBACK,'route'=>HP10_ROUTE,'method'=>$_SERVER['REQUEST_METHOD'] ?? '','timestamp'=>gmdate('c'),'pid'=>getmypid()]; });
 uopz_set_hook('WP_REST_Request','get_param',static function ($key) use ($hp10_id,$hp10_add): void { $id=$hp10_id(); if ($id==='' || !is_string($key)) return; $target=false; foreach (debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS,12) as $f) if (($f['class'] ?? '')==='WPCF7_REST_Controller' && ($f['function'] ?? '')==='get_contact_forms') { $target=true; break; } if (!$target) return; $present=array_key_exists($key,$_GET); $value=$present && is_scalar($_GET[$key])?(string)$_GET[$key]:''; $expectedKey=$_SERVER['HTTP_X_HOOKPHUZZ_EXPECTED_KEY'] ?? ''; $expectedHash=$_SERVER['HTTP_X_HOOKPHUZZ_EXPECTED_VALUE_SHA256'] ?? ''; $marker=$_SERVER['HTTP_X_HOOKPHUZZ_PROBE_MARKER'] ?? ''; $valueHash=$present?hash('sha256',$value):null; $hp10_add(['request_id'=>$id,'route'=>HP10_ROUTE,'http_method'=>$_SERVER['REQUEST_METHOD'] ?? '','callback_id'=>HP10_CALLBACK,'transport_source'=>'GET/query','request_api'=>'WP_REST_Request','access_mechanism'=>'WP_REST_Request::get_param','parameter_key'=>$key,'path'=>[$key],'input_present'=>$present,'typed_value_match'=>$present && $key===$expectedKey && is_string($expectedHash) && hash_equals($expectedHash,$valueHash ?? ''),'marker_match'=>$present && $key==='search' && $key===$expectedKey && is_string($marker) && hash_equals(hash('sha256',$marker),$valueHash ?? ''),'marker_sha256'=>is_string($marker)?hash('sha256',$marker):null,'value_sha256'=>$valueHash,'timestamp'=>gmdate('c'),'pid'=>getmypid()]); });
},PHP_INT_MAX);
register_shutdown_function(static function () use (&$hp10_doc,$hp10_id): void { $id=$hp10_id(); if ($id==='') return; $hp10_doc['request_id']=$id;$hp10_doc['route']=HP10_ROUTE;$hp10_doc['method']=$_SERVER['REQUEST_METHOD'] ?? '';$hp10_doc['pid']=getmypid();$hp10_doc['uri']=parse_url($_SERVER['REQUEST_URI'] ?? '',PHP_URL_PATH) ?: '/';$hp10_doc['timestamp']=gmdate('c');$dir='/results/runtime';if (!is_dir($dir)) mkdir($dir,0700,true);$tmp=tempnam($dir,'.tmp-');$json=json_encode($hp10_doc,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);if ($tmp!==false && $json!==false && file_put_contents($tmp,$json,LOCK_EX)!==false) rename($tmp,"$dir/$id.rest.json");elseif($tmp!==false)@unlink($tmp);});
