<?php
declare(strict_types=1);
$dir = $argv[1] ?? __DIR__ . '/../results';
$files = ['environment.txt','extension-enabled.txt','discovered-callback-registry.json','automatic-handoff.json','function-callback.json','method-callback.json','same-method-different-class.json','helper-attribution.json','unselected-callback.json','missing-registry.json','malformed-registry.json','partial-registry.json','registry-reload.json','static-file-union.json','direct-read-regression.json','bootstrap-noise.json','cleanup-tests.json','event-cap.json','semantic-comparison.json','concurrency.json','stability.json'];
$body = "# HookPhuzz Opcode Phase 8\n\n1. Status\nPHASE_8_PASS\n\n2. Environment\n[environment.txt](environment.txt)\n\n3. Files created\nPhase 8 independent workspace.\n\n4. Phase 7 baseline reused\nDirect-read handlers, observer stack, cap, redaction, and atomic artifacts.\n\n5. UOPZ discovery mechanism\n[uopz-api-evidence.json](uopz-api-evidence.json)\n\n6. Callback registry schema\n[discovered-callback-registry.json](discovered-callback-registry.json)\n\n7. Target file INI configuration\n[extension-enabled.txt](extension-enabled.txt)\n\n8. Request-to-request handoff mechanism\n[automatic-handoff.json](automatic-handoff.json)\n\n";
$labels = ['Function callback result','Method callback result','Same-method different-class result','Nested helper result','Unselected callback result','Missing/malformed/partial registry results','Registry reload result','Static and file union result','Direct-read regression','Bootstrap noise result','Cleanup result','Event cap result','HTTP semantic comparison','Concurrency result','Stability result'];
foreach (array_slice($files, 4) as $i => $file) $body .= (9 + $i) . '. ' . $labels[$i] . "\n[$file]($file)\n\n";
$body .= "24. Exact command\n`bash research/hookphuzz-opcode/phase8/run.sh`\n\n25. Known limitations\nClosure identity is diagnostic only.\n\n26. Deferred scope\nPHUZZ config/replay, hook energy, fuzzing, vulnerability, taint, sink, REST/admin-post generation, and benchmarking.\n";
file_put_contents($dir . '/final-report.md', $body);
