#!/usr/bin/env python3
import argparse,json
from pathlib import Path
REQUIRED=['environment.txt','tls-scan.txt','plugin-state.json','rest-route-registration.json','rest-route-resolution.json','source-analysis.json','source-analysis.md','raw-opcode-events.json','raw-rest-helper-events.json','callback-evidence.json','normalized-params.json','generated-config.json','replay-validation.json','negative-tests.json']
def load(p): return json.loads(p.read_text())
def main():
 p=argparse.ArgumentParser();p.add_argument('--results',required=True);p.add_argument('--run-id',required=True);a=p.parse_args();r=Path(a.results);missing=[x for x in REQUIRED if not (r/x).is_file()];n=load(r/'normalized-params.json');replay=load(r/'replay-validation.json');negative=load(r/'negative-tests.json');route=load(r/'rest-route-registration.json');resolution=load(r/'rest-route-resolution.json');plugin=load(r/'plugin-state.json')
 gates={'environment_ready':not missing,'plugin_installed':plugin.get('installed') is True,'plugin_active':plugin.get('active') is True,'rest_api_ready':resolution.get('rest_api_ready') is True,'route_discovered':route.get('route_discovered') is True,'route_callback_resolved':route.get('callback_id')=='WPCF7_REST_Controller::get_contact_forms','request_route_resolved':resolution.get('effective_mode') in {'canonical','fallback'},'request_sent':resolution.get('request_sent') is True,'callback_reached':load(r/'callback-evidence.json').get('callback_reached') is True,'runtime_parameter_observed':len(n.get('parameters',[]))==5,'source_runtime_separation_pass':n.get('source_runtime_separation_pass') is True,'normalized_params_valid':all(x.get('runtime_observed') for x in n.get('parameters',[])),'generated_config_valid':(r/'generated-config.json').is_file(),'replay_request_sent':replay.get('replay_request_sent') is True,'replay_callback_reached':replay.get('replay_callback_reached') is True,'replay_parameter_observed':replay.get('replay_parameter_observed') is True,'parameter_path_matched':replay.get('parameter_path_matched') is True,'marker_or_typed_value_matched':replay.get('marker_or_typed_value_matched') is True,'isolation_pass':negative.get('tests',{}).get('marker_isolation') is True,'concurrency_pass':negative.get('tests',{}).get('concurrency') is True,'negative_tests_pass':negative.get('passed') is True,'tls_scan_pass':(r/'tls-scan.txt').read_text().strip()=='TLS_SCAN_PASS','artifact_validation_pass':not missing}
 status='PHASE_10_CF7_REST_PASS' if all(gates.values()) else 'PHASE_10_CF7_REST_FAIL';(r/'gate-summary.json').write_text(json.dumps({'schema_version':1,'run_id':a.run_id,'status':status,'gates':gates,'missing_artifacts':missing},indent=2)+'\n')
 lines=['# Phase 10 CF7 REST final report','',f'## Status\n\n`{status}`','',f'Run ID: `{a.run_id}`.','', '## Confirmed scope','', '- Current-run WordPress REST registration and server state were used.','- Source candidates remain separate from runtime helper events.','- CF7 reads through `WP_REST_Request::get_param`; no synthetic opcode event was emitted.','- No vulnerability benchmark or PHUZZ main-pipeline integration.','', '## Gates','']+[f'- {k}: **{"PASS" if v else "FAIL"}**' for k,v in gates.items()]
 (r/'final-report.md').write_text('\n'.join(lines)+'\n');print(status);raise SystemExit(0 if status.endswith('PASS') else 1)
if __name__=='__main__':main()
