<?php
declare(strict_types=1);
function readJson(string $path): ?array { try { return json_decode((string)file_get_contents($path),true,512,JSON_THROW_ON_ERROR); } catch (Throwable) { return null; } }
function gate(array &$gates,string $name,bool $passed,string $evidence,array $extra=[]): void { $gates[$name]=array_merge(['passed'=>$passed,'evidence'=>$evidence],$extra); }
[$script,$results,$runId]=$argv+['','',''];if(!$results||!$runId)exit(2);
$registry=readJson("$results/discovered-callback-registry.json");$source=readJson("$results/source-resolution.json");$negative=readJson("$results/source-resolution-negative.json");$replay=readJson("$results/replay-validation-summary.json");$noise=readJson("$results/bootstrap-noise-isolation.json");$duplicate=readJson("$results/duplicate-helper-summary.json");$concurrency=readJson("$results/concurrency-summary.json");$stability=readJson("$results/stability-summary.json");$configs=readJson("$results/generated-configs.json");
$g=[];$e=static fn(string $name)=>"results/$name";
$registryPass=is_array($registry)&&($registry['schema_version']??null)===1&&count($registry['registrations']??[])>0;gate($g,'registry_discovery',$registryPass,$e('discovered-callback-registry.json'),['count'=>count($registry['registrations']??[])]);
$checks=[];foreach($source['checks']??[] as $check)$checks[$check['label']??'']=$check;
foreach(['direct-get'=>'direct_get_mapping','direct-post'=>'direct_post_mapping','direct-cookie'=>'direct_cookie_mapping'] as $label=>$name)gate($g,$name,(($source['run_id']??null)===$runId&&($checks[$label]['ok']??false)===true),$e('source-resolution.json'));
$requestPass=($source['run_id']??null)===$runId&&($source['status']??null)==='validated'&&($source['accepted_placements']??[])===['query','body'];gate($g,'request_source_resolution',$requestPass,$e('source-resolution.json'),['accepted_placements'=>$source['accepted_placements']??[]]);
gate($g,'request_precedence',$requestPass&&($source['precedence_winner']??null)==='body',$e('source-resolution.json'));
$variants=[];foreach($configs['configs']??[] as $config)if(($config['request_variant']??null)!==null)$variants[]=$config['request_variant'];$variantPass=in_array('query',$variants,true)&&in_array('body',$variants,true);gate($g,'generated_config_variants',$variantPass,$e('generated-configs.json'),['variants'=>array_values(array_unique($variants))]);
$negativePass=($negative['run_id']??null)===$runId&&($negative['status']??null)==='PASS'&&($negative['wrong_placement']??false)===true&&($negative['missing_parameter']??false)===true&&($negative['wrong_key']??false)===true&&($negative['stale_artifact']??false)===true&&($negative['mismatched_request_id']??false)===true;gate($g,'negative_semantic_suite',$negativePass,$e('source-resolution-negative.json'));
$nullMarker=static fn($check)=>is_array($check)&&array_key_exists('observed_marker',$check)&&$check['observed_marker']===null;$markerPass=$negativePass&&$nullMarker($checks['request-missing']??null)&&$nullMarker($checks['request-wrong-key']??null);gate($g,'actual_parameter_marker_validation',$markerPass,$e('source-resolution.json'));
$auth=false;foreach($replay['results']??[] as $result)if(($result['hook_name']??null)==='wp_ajax_hookphuzz_phase9_authenticated'&&($result['semantic_equivalent']??false)===true)$auth=true;gate($g,'authenticated_replay',$auth,$e('replay-validation-summary.json'));
$fullReplay=($replay['run_id']??null)===$runId&&($replay['summary']['all_semantic_pass']??false)===true&&($replay['summary']['total_configs']??0)>0;gate($g,'full_generated_config_replay',$fullReplay,$e('replay-validation-summary.json'),['configs'=>$replay['summary']['total_configs']??0]);
gate($g,'bootstrap_noise_isolation',($noise['run_id']??null)===$runId&&($noise['passed']??false)===true,$e('bootstrap-noise-isolation.json'));
gate($g,'duplicate_helper_runtime',($duplicate['run_id']??null)===$runId&&($duplicate['passed']??false)===true,$e('duplicate-helper-summary.json'));
gate($g,'parameter_deduplication',($duplicate['run_id']??null)===$runId&&($duplicate['deduplication_pass']??false)===true,$e('duplicate-helper-summary.json'));
foreach([['concurrency_20',$concurrency,20,'concurrency-summary.json'],['stability_300',$stability,300,'stability-summary.json']] as [$name,$summary,$count,$file]){$pass=($summary['run_id']??null)===$runId&&($summary['passed']??false)===true&&($summary['requests_sent']??0)===$count&&($summary['semantic_passes']??0)===$count&&($summary['valid_artifacts']??0)===$count;gate($g,$name,$pass,$e($file),['requests_sent'=>$summary['requests_sent']??0]);}
$allCurrent=true;foreach([$source,$negative,$replay,$noise,$duplicate,$concurrency,$stability] as $summary)if(($summary['run_id']??null)!==$runId)$allCurrent=false;foreach(glob("$results/artifacts/*.json")?:[] as $artifactFile){$artifact=readJson($artifactFile);if(($artifact['run_id']??null)!==$runId)$allCurrent=false;}gate($g,'all_artifacts_current_run',$allCurrent,$e('run-id.txt'));
$failed=array_keys(array_filter($g,static fn($v)=>($v['passed']??false)!==true));$out=['schema_version'=>1,'run_id'=>$runId,'generated_at'=>gmdate('c'),'environment_evidence'=>$e('environment.txt'),'registry_discovery'=>$g['registry_discovery'],'direct_get_mapping'=>$g['direct_get_mapping'],'direct_post_mapping'=>$g['direct_post_mapping'],'direct_cookie_mapping'=>$g['direct_cookie_mapping'],'request_source_resolution'=>$g['request_source_resolution'],'request_precedence'=>$g['request_precedence'],'generated_config_variants'=>$g['generated_config_variants'],'actual_parameter_marker_validation'=>$g['actual_parameter_marker_validation'],'negative_semantic_suite'=>$g['negative_semantic_suite'],'authenticated_replay'=>$g['authenticated_replay'],'full_generated_config_replay'=>$g['full_generated_config_replay'],'bootstrap_noise_isolation'=>$g['bootstrap_noise_isolation'],'duplicate_helper_runtime'=>$g['duplicate_helper_runtime'],'parameter_deduplication'=>$g['parameter_deduplication'],'concurrency_20'=>$g['concurrency_20'],'stability_300'=>$g['stability_300'],'all_artifacts_current_run'=>$g['all_artifacts_current_run'],'failed_gates'=>$failed,'overall_pass'=>$failed===[]];$path="$results/phase9-validation-summary.json";$tmp=$path.'.tmp.'.getmypid();file_put_contents($tmp,json_encode($out,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);rename($tmp,$path);foreach($failed as $name)fwrite(STDERR,"failed_gate:$name\n");exit($failed===[]?0:1);
