<?php
declare(strict_types=1);
[$script,$artifactPath,$configsPath,$output,$runId]=$argv+['','','','',''];
try{$artifact=json_decode((string)file_get_contents($artifactPath),true,512,JSON_THROW_ON_ERROR);$configs=json_decode((string)file_get_contents($configsPath),true,512,JSON_THROW_ON_ERROR);}catch(Throwable){fwrite(STDERR,"duplicate helper evidence malformed\n");exit(1);}
$root='hookphuzz_phase9_duplicate_probe';$events=array_values(array_filter($artifact['events']??[],static fn($e)=>($e['callback_context']['root_callback']??null)===$root&&($e['source']??null)==='POST'&&($e['path']??null)===['duplicate_key']));
$helper=array_values(array_filter($events,static fn($e)=>(int)($e['callback_context']['depth']??0)>=1));
$summary=array_values(array_filter($artifact['callback_summaries']??[],static fn($s)=>($s['callback']??null)===$root))[0]??[];
$params=array_values(array_filter($summary['unique_parameters']??[],static fn($p)=>($p['source']??null)==='POST'&&($p['path']??null)===['duplicate_key']));
$configsForParameter=[];foreach($configs['configs']??[] as $config)if(($config['callback']??null)===$root)foreach($config['discovered_parameters']??[] as $p)if(($p['observed_source']??null)==='POST'&&($p['path']??null)===['duplicate_key'])$configsForParameter[]=$config['config_id'];
$uniqueConfigs=array_values(array_unique($configsForParameter));$raw=count($events);$expected=3;$rootMatch=$raw===$expected;$helperPass=count($helper)>=1;$dedup=count($params)===1&&($params[0]['observed_count']??0)===$expected&&count($uniqueConfigs)===1;$pass=($artifact['run_id']??null)===$runId&&$rootMatch&&$helperPass&&$dedup;
$out=['schema_version'=>1,'run_id'=>$runId,'request_id'=>$artifact['request_id']??null,'root_callback'=>$root,'helper_callback'=>'hookphuzz_phase9_duplicate_helper','helper_frame_evidence'=>array_map(static fn($e)=>['depth'=>$e['callback_context']['depth']??null,'callback'=>$e['callback_context']['callback']??null],$helper),'raw_read_event_count'=>$raw,'matching_read_event_count'=>$raw,'expected_raw_read_event_count'=>$expected,'unique_parameter_count'=>count($params),'generated_config_count'=>count($uniqueConfigs),'duplicate_config_count'=>count($configsForParameter)-count($uniqueConfigs),'root_callback_match'=>$rootMatch,'helper_attribution_pass'=>$helperPass,'deduplication_pass'=>$dedup,'passed'=>$pass];$tmp=$output.'.tmp.'.getmypid();file_put_contents($tmp,json_encode($out,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX);rename($tmp,$output);exit($pass?0:1);
