#!/usr/bin/env bash
set -euo pipefail
results=${1:?results}; artifacts=${2:?artifacts}; run_id=${3:?run id}; mkdir -p "$results/source-probes"
wait_artifact(){ local id=$1; for _ in $(seq 1 200);do [[ -f "$artifacts/$id.json" ]]&&{ echo "$artifacts/$id.json";return;};sleep .1;done;return 1; }
probe(){ local label=$1 action=$2 placement=$3 marker=$4 source=$5 callback=$6 expect=${7:-true}; local id="$run_id-$label" url="http://enabled/wp-admin/admin-ajax.php?action=$action"; local args=(-sS --max-time 20 -H "X-Fuzzer-Covid: $id" -H "X-Phase9-Run-ID: $run_id" -H "X-Phase9-Marker: $marker" -o "$results/source-probes/$label.body" -w '%{http_code}'); case $placement in query)url+="&phase9_key=$marker";;wrongkey)url+="&phase9_wrong_key=$marker";;body)args+=(--data-urlencode "phase9_key=$marker");;cookie)args+=(-b "phase9_key=$marker");;esac; [[ $label == direct-get ]] && url+='&phase9_bootstrap_noise=PHASE9_NOISE'; [[ $(curl "${args[@]}" "$url") == 200 ]] || return 1; local a; a=$(wait_artifact "$id"); cp "$a" "$results/artifacts/source-$label.json"; printf '{"id":"%s","label":"%s","run_id":"%s","placement":"%s","expected_marker":"%s","runtime_source":"%s","callback":"%s","body":"%s","artifact":"%s","request_order":"GP","variables_order":"GPCS","expect_observed":%s}\n' "$id" "$label" "$run_id" "$placement" "$marker" "$source" "$callback" "$results/source-probes/$label.body" "$a" "$expect" >> "$results/source-probes/manifest.jsonl"; }
: > "$results/source-probes/manifest.jsonl"
probe direct-get hookphuzz_phase9_get_probe query PHASE9_GET GET hookphuzz_phase9_get_probe
probe direct-post hookphuzz_phase9_post_probe body PHASE9_POST POST hookphuzz_phase9_post_probe
probe direct-cookie hookphuzz_phase9_cookie_probe cookie PHASE9_COOKIE COOKIE hookphuzz_phase9_cookie_probe
probe request-query hookphuzz_phase9_request_probe query PHASE9_REQUEST_QUERY REQUEST hookphuzz_phase9_request_probe
probe request-body hookphuzz_phase9_request_probe body PHASE9_REQUEST_BODY REQUEST hookphuzz_phase9_request_probe
probe request-cookie hookphuzz_phase9_request_probe cookie PHASE9_REQUEST_COOKIE REQUEST hookphuzz_phase9_request_probe false
probe request-missing hookphuzz_phase9_request_probe none PHASE9_REQUEST_MISSING REQUEST hookphuzz_phase9_request_probe false
probe request-wrong-key hookphuzz_phase9_request_probe wrongkey PHASE9_REQUEST_WRONG REQUEST hookphuzz_phase9_request_probe false
id="$run_id-request-precedence"; marker=PHASE9_PRECEDENCE_BODY; [[ $(curl -sS --max-time 20 -H "X-Fuzzer-Covid: $id" -H "X-Phase9-Run-ID: $run_id" -H "X-Phase9-Marker: $marker" -b 'phase9_key=PHASE9_PRECEDENCE_COOKIE' --data-urlencode 'phase9_key=PHASE9_PRECEDENCE_BODY' -o "$results/source-probes/request-precedence.body" -w '%{http_code}' 'http://enabled/wp-admin/admin-ajax.php?action=hookphuzz_phase9_request_probe&phase9_key=PHASE9_PRECEDENCE_QUERY') == 200 ]]
a=$(wait_artifact "$id"); printf '{"id":"%s","label":"request-precedence","run_id":"%s","placement":"precedence","expected_marker":"%s","runtime_source":"REQUEST","callback":"hookphuzz_phase9_request_probe","body":"%s","artifact":"%s","request_order":"GP","variables_order":"GPCS"}\n' "$id" "$run_id" "$marker" "$results/source-probes/request-precedence.body" "$a" >> "$results/source-probes/manifest.jsonl"
php -r '$a=[]; foreach(file($argv[1],FILE_IGNORE_NEW_LINES) as $l)$a[]=json_decode($l,true); file_put_contents($argv[2],json_encode($a));' "$results/source-probes/manifest.jsonl" "$results/source-probes/manifest.json"
php /workspace/tests/source-resolution.php "$results/source-probes/manifest.json" "$results/source-resolution.json" "$run_id"
php -r '$a=json_decode(file_get_contents($argv[1]),true); $a[0]["id"]="mismatched-request-id"; file_put_contents($argv[2],json_encode([$a[0]])); $a[0]["artifact"]=$argv[3]; file_put_contents($argv[4],json_encode([$a[0]]));' "$results/source-probes/manifest.json" "$results/source-probes/bad-id.json" "$artifacts/request-body.json" "$results/source-probes/stale.json"
bad_id_rejected=false; stale_rejected=false
if php /workspace/tests/source-resolution.php "$results/source-probes/bad-id.json" "$results/source-probes/bad-id.out" "$run_id" 2>/dev/null; then exit 1; else bad_id_rejected=true; fi
if php /workspace/tests/source-resolution.php "$results/source-probes/stale.json" "$results/source-probes/stale.out" "$run_id" 2>/dev/null; then exit 1; else stale_rejected=true; fi
php -r '$source=json_decode(file_get_contents($argv[1]),true); $checks=[]; foreach($source["checks"]??[] as $check)$checks[$check["label"]??""]=$check; $null=static fn($c)=>is_array($c)&&array_key_exists("observed_marker",$c)&&$c["observed_marker"]===null; $out=["run_id"=>$argv[2],"wrong_placement"=>$null($checks["request-cookie"]??null),"missing_parameter"=>$null($checks["request-missing"]??null),"wrong_key"=>$null($checks["request-wrong-key"]??null),"stale_artifact"=>filter_var($argv[3],FILTER_VALIDATE_BOOLEAN),"mismatched_request_id"=>filter_var($argv[4],FILTER_VALIDATE_BOOLEAN)]; $out["status"]=!in_array(false,$out,true)?"PASS":"FAIL"; file_put_contents($argv[5].".tmp",json_encode($out,JSON_PRETTY_PRINT)); rename($argv[5].".tmp",$argv[5]); exit($out["status"]==="PASS"?0:1);' "$results/source-resolution.json" "$run_id" "$stale_rejected" "$bad_id_rejected" "$results/source-resolution-negative.json"
